### ISSUE TITLE
how to merge SV callings from Pariament2 and sinffle results

### ISSUE THREAD

**Issue by zhoudreames** [marbl/CHM13-issues#7]
I had two SV Calling resultings from Pariament2 and sinffle software showing in blow:
Pariament2:
![image](https://user-images.githubusercontent.com/54714639/148155951-a4c4fa22-246d-49fe-a8c7-0fb46ac49c3a.png)
sinffle:
![image](https://user-images.githubusercontent.com/54714639/148156009-8f21ba1d-d5bf-4fa5-8b23-a64c20773dc1.png)
Frist,there  are no base information instead of “DEL001207SUR” in the pariament2 resulting，how to transform it into base format just like sinffle resulting.
Second,how to merge two SV calling resulting according to your  SVs format showing blow?
![image](https://user-images.githubusercontent.com/54714639/148156497-40e70d5a-56d6-4cb1-80b3-a5ab1f89f3e2.png)

**Comment by zhoudreames** [comment]
in addtion,Can I polish  inversion ？

**Comment by arangrhie** [comment]
Please refer to [this part](https://github.com/marbl/CHM13-issues/blob/main/error_detection.md#sv-like-error-detection). More details can be found in the [polishing paper](https://doi.org/10.1101/2021.07.02.450803), with the codes in [this repo](https://github.com/arangrhie/T2T-Polish). Please open an issue in the T2T-Polish repo if you need additional assistance or clarifications.

Inversions weren't found in our SV-error detection. Note a lot of SV calls turned out to be false positives. I'd be cautious to attempt doing any automatic polishing on inversions, especially if the SVs are within contigs and do a manual validation.

As long as the REF and ALT sequences are valid, `bcftools consensus` will be happy to replace the REF to ALT sequence, regardless being an INV or not.
